service: nodemoduleslayer

frameworkVersion: '2'

plugins:
  - serverless-plugin-scripts
  - serverless-offline

package:
  excludeDevDependencies: false
  exclude:
    - layer_modules/**

custom:
  scripts:
    hooks:
      'package:initialize': cd layer_modules && npm install

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

layers:
  lambdaLayerModule:
    path: layer_modules
    name: ${self:service}-${self:provider.stage}
    description: layers of modules for dependencies
    compatibleRuntimes:
      - nodejs12.x
      - nodejs14.x
    retain: true
